# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_pc_cpp <- function(data, col_names, alpha, depth, verbose, knowledge_ptr) {
    .Call(`_rtetrad_run_pc_cpp`, data, col_names, alpha, depth, verbose, knowledge_ptr)
}

run_fges_cpp <- function(data, col_names, penalty_discount, faithfulness_assumed, max_degree, verbose, knowledge_ptr) {
    .Call(`_rtetrad_run_fges_cpp`, data, col_names, penalty_discount, faithfulness_assumed, max_degree, verbose, knowledge_ptr)
}

run_gfci_cpp <- function(data, col_names, alpha, penalty_discount, depth, max_degree, complete_rule_set, max_disc_path_length, faithfulness_assumed, verbose, knowledge_ptr) {
    .Call(`_rtetrad_run_gfci_cpp`, data, col_names, alpha, penalty_discount, depth, max_degree, complete_rule_set, max_disc_path_length, faithfulness_assumed, verbose, knowledge_ptr)
}

create_knowledge_cpp <- function() {
    .Call(`_rtetrad_create_knowledge_cpp`)
}

knowledge_set_forbidden_cpp <- function(ptr, from, to) {
    invisible(.Call(`_rtetrad_knowledge_set_forbidden_cpp`, ptr, from, to))
}

knowledge_set_required_cpp <- function(ptr, from, to) {
    invisible(.Call(`_rtetrad_knowledge_set_required_cpp`, ptr, from, to))
}

knowledge_set_tier_cpp <- function(ptr, tier, vars) {
    invisible(.Call(`_rtetrad_knowledge_set_tier_cpp`, ptr, tier, vars))
}

knowledge_set_tier_forbidden_within_cpp <- function(ptr, tier, forbidden) {
    invisible(.Call(`_rtetrad_knowledge_set_tier_forbidden_within_cpp`, ptr, tier, forbidden))
}

set_log_stream_rcout_cpp <- function() {
    invisible(.Call(`_rtetrad_set_log_stream_rcout_cpp`))
}

