// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_pc_cpp
Rcpp::List run_pc_cpp(Eigen::Map<Eigen::MatrixXd> data, Rcpp::CharacterVector col_names, double alpha, int depth, bool verbose, SEXP knowledge_ptr);
RcppExport SEXP _rtetrad_run_pc_cpp(SEXP dataSEXP, SEXP col_namesSEXP, SEXP alphaSEXP, SEXP depthSEXP, SEXP verboseSEXP, SEXP knowledge_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type knowledge_ptr(knowledge_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(run_pc_cpp(data, col_names, alpha, depth, verbose, knowledge_ptr));
    return rcpp_result_gen;
END_RCPP
}
// run_fges_cpp
Rcpp::List run_fges_cpp(Eigen::Map<Eigen::MatrixXd> data, Rcpp::CharacterVector col_names, double penalty_discount, bool faithfulness_assumed, int max_degree, bool verbose, SEXP knowledge_ptr);
RcppExport SEXP _rtetrad_run_fges_cpp(SEXP dataSEXP, SEXP col_namesSEXP, SEXP penalty_discountSEXP, SEXP faithfulness_assumedSEXP, SEXP max_degreeSEXP, SEXP verboseSEXP, SEXP knowledge_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_discount(penalty_discountSEXP);
    Rcpp::traits::input_parameter< bool >::type faithfulness_assumed(faithfulness_assumedSEXP);
    Rcpp::traits::input_parameter< int >::type max_degree(max_degreeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type knowledge_ptr(knowledge_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(run_fges_cpp(data, col_names, penalty_discount, faithfulness_assumed, max_degree, verbose, knowledge_ptr));
    return rcpp_result_gen;
END_RCPP
}
// run_gfci_cpp
Rcpp::List run_gfci_cpp(Eigen::Map<Eigen::MatrixXd> data, Rcpp::CharacterVector col_names, double alpha, double penalty_discount, int depth, int max_degree, bool complete_rule_set, int max_disc_path_length, bool faithfulness_assumed, bool verbose, SEXP knowledge_ptr);
RcppExport SEXP _rtetrad_run_gfci_cpp(SEXP dataSEXP, SEXP col_namesSEXP, SEXP alphaSEXP, SEXP penalty_discountSEXP, SEXP depthSEXP, SEXP max_degreeSEXP, SEXP complete_rule_setSEXP, SEXP max_disc_path_lengthSEXP, SEXP faithfulness_assumedSEXP, SEXP verboseSEXP, SEXP knowledge_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_discount(penalty_discountSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type max_degree(max_degreeSEXP);
    Rcpp::traits::input_parameter< bool >::type complete_rule_set(complete_rule_setSEXP);
    Rcpp::traits::input_parameter< int >::type max_disc_path_length(max_disc_path_lengthSEXP);
    Rcpp::traits::input_parameter< bool >::type faithfulness_assumed(faithfulness_assumedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type knowledge_ptr(knowledge_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(run_gfci_cpp(data, col_names, alpha, penalty_discount, depth, max_degree, complete_rule_set, max_disc_path_length, faithfulness_assumed, verbose, knowledge_ptr));
    return rcpp_result_gen;
END_RCPP
}
// create_knowledge_cpp
SEXP create_knowledge_cpp();
RcppExport SEXP _rtetrad_create_knowledge_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(create_knowledge_cpp());
    return rcpp_result_gen;
END_RCPP
}
// knowledge_set_forbidden_cpp
void knowledge_set_forbidden_cpp(SEXP ptr, std::string from, std::string to);
RcppExport SEXP _rtetrad_knowledge_set_forbidden_cpp(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type from(fromSEXP);
    Rcpp::traits::input_parameter< std::string >::type to(toSEXP);
    knowledge_set_forbidden_cpp(ptr, from, to);
    return R_NilValue;
END_RCPP
}
// knowledge_set_required_cpp
void knowledge_set_required_cpp(SEXP ptr, std::string from, std::string to);
RcppExport SEXP _rtetrad_knowledge_set_required_cpp(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type from(fromSEXP);
    Rcpp::traits::input_parameter< std::string >::type to(toSEXP);
    knowledge_set_required_cpp(ptr, from, to);
    return R_NilValue;
END_RCPP
}
// knowledge_set_tier_cpp
void knowledge_set_tier_cpp(SEXP ptr, int tier, std::vector<std::string> vars);
RcppExport SEXP _rtetrad_knowledge_set_tier_cpp(SEXP ptrSEXP, SEXP tierSEXP, SEXP varsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type tier(tierSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type vars(varsSEXP);
    knowledge_set_tier_cpp(ptr, tier, vars);
    return R_NilValue;
END_RCPP
}
// knowledge_set_tier_forbidden_within_cpp
void knowledge_set_tier_forbidden_within_cpp(SEXP ptr, int tier, bool forbidden);
RcppExport SEXP _rtetrad_knowledge_set_tier_forbidden_within_cpp(SEXP ptrSEXP, SEXP tierSEXP, SEXP forbiddenSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type tier(tierSEXP);
    Rcpp::traits::input_parameter< bool >::type forbidden(forbiddenSEXP);
    knowledge_set_tier_forbidden_within_cpp(ptr, tier, forbidden);
    return R_NilValue;
END_RCPP
}
// set_log_stream_rcout_cpp
void set_log_stream_rcout_cpp();
RcppExport SEXP _rtetrad_set_log_stream_rcout_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    set_log_stream_rcout_cpp();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtetrad_run_pc_cpp", (DL_FUNC) &_rtetrad_run_pc_cpp, 6},
    {"_rtetrad_run_fges_cpp", (DL_FUNC) &_rtetrad_run_fges_cpp, 7},
    {"_rtetrad_run_gfci_cpp", (DL_FUNC) &_rtetrad_run_gfci_cpp, 11},
    {"_rtetrad_create_knowledge_cpp", (DL_FUNC) &_rtetrad_create_knowledge_cpp, 0},
    {"_rtetrad_knowledge_set_forbidden_cpp", (DL_FUNC) &_rtetrad_knowledge_set_forbidden_cpp, 3},
    {"_rtetrad_knowledge_set_required_cpp", (DL_FUNC) &_rtetrad_knowledge_set_required_cpp, 3},
    {"_rtetrad_knowledge_set_tier_cpp", (DL_FUNC) &_rtetrad_knowledge_set_tier_cpp, 3},
    {"_rtetrad_knowledge_set_tier_forbidden_within_cpp", (DL_FUNC) &_rtetrad_knowledge_set_tier_forbidden_within_cpp, 3},
    {"_rtetrad_set_log_stream_rcout_cpp", (DL_FUNC) &_rtetrad_set_log_stream_rcout_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtetrad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
